spring.application.name=chatbotEAM-Backend

server.port=9698

#spring.datasource.url=jdbc:postgresql://localhost:5432/eam-chatbot
spring.datasource.url=jdbc:postgresql://postgres:5432/eam-chatbot
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update